include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_return: error
    missing_required_param: error
  language:
    strict-raw-types: true

linter:
  rules:
    # Errors prevention
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    use_build_context_synchronously: true

    # Style consistency
    prefer_single_quotes: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    use_decorated_box: true

    # Code quality
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    require_trailing_commas: true
